//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ficality
{
    using System;
    using System.Collections.Generic;
    
    public partial class student_table
    {
        public int stu_id { get; set; }
        public string stu_name { get; set; }
        public string stu_address { get; set; }
        public string stu_age { get; set; }
        public string stu_department { get; set; }
    }
}
